"""
chat.py
-------
Phase 12: POST /chat/ — LLM-powered repository RAG chatbot endpoint.
          GET  /chat/stream — SSE streaming variant.

The vector store is built once during /analyze/ and reused here.
Answers are generated by Groq LLM grounded strictly on retrieved chunks.

Non-streaming response shape:
    {
        "answer":     str,
        "sources":    list[str],
        "confidence": "high" | "medium" | "low"
    }

Streaming response:
    Content-Type: text/event-stream
    data: <token>\\n\\n   (repeated)
    data: [META] {"sources": [...], "confidence": "..."}\\n\\n
    data: [DONE]\\n\\n
"""

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.services.retriever import get_store, query_store
from app.services.embeddings import get_model
from app.services.rag_chat import answer_question
from app.services.llm_service import stream_answer_tokens
from app.services.repo_metadata import (
    is_metadata_question,
    answer_metadata_question,
    stream_metadata_answer,
    get_cached_metadata,
)
import app.services.cache_db as cache_db

router = APIRouter(prefix="/chat", tags=["chat"])


def _try_restore_store(repo_url: str):
    """
    Attempt to restore the RAG vector store from the PostgreSQL cache.
    Called when get_store() returns None (e.g. after a server restart).
    Returns the restored VectorStore on success, None on failure.
    """
    if not cache_db.is_available():
        return None
    try:
        print(f"[rag] store missing for {repo_url} — attempting DB restore")
        cached = cache_db.get_cached_analysis(repo_url)
        if cached is None:
            print(f"[rag] repo not found in DB cache: {repo_url}")
            return None
        embeddings = cached.get("embeddings")
        chunks     = cached.get("chunks")
        if embeddings is None or not chunks:
            print(f"[rag] DB cache has no embeddings/chunks for {repo_url}")
            return None
        from app.services.retriever import restore_store
        print(f"[rag] restoring embeddings")
        store = restore_store(repo_url, embeddings, chunks)
        print(f"[rag] restore successful")
        print(f"[rag] restored {store.size} chunks from DB for {repo_url}")
        return store
    except Exception as exc:
        print(f"[rag] DB restore failed: {exc}")
        return None

def _trigger_lightweight_rebuild(repo_url: str):
    print(f"[rag] triggering lightweight rebuild for {repo_url}")
    from app.services.github_fetcher import fetch_repo_fast
    from app.services.embeddings import build_chunks, get_model
    from app.services.retriever import build_store, serialize_store
    import app.services.cache_db as cache_db
    
    scan_data, file_contents = fetch_repo_fast(repo_url)
    if not file_contents:
        print("[rag] lightweight rebuild failed — could not fetch files")
        return None
    
    extra_context = {}
    cached = cache_db.get_cached_analysis(repo_url) if cache_db.is_available() else None
    if cached and cached.get("analysis"):
        analysis = cached["analysis"]
        extra_context = {
            "ai_explanation": analysis.get("ai_explanation", ""),
            "folder_explanations": analysis.get("folder_explanations", {}),
            "api_routes": analysis.get("api_routes", []),
            "important_files": analysis.get("important_files", []),
        }

    chunks = build_chunks(file_contents, extra_context=extra_context)
    model = get_model()
    store = build_store(repo_url, chunks, model)
    
    if cached:
        emb, chk = serialize_store(store)
        cache_db.upsert_analysis(
            repo_url=repo_url,
            commit_sha=cached.get("sha", "unknown"),
            analysis=cached.get("analysis", {}),
            embeddings=emb,
            chunks=chk
        )
    
    return store
class ChatRequest(BaseModel):
    repo_url: str
    question: str


# ── Blocking endpoint ─────────────────────────────────────────────────────────

@router.post("/")
def chat(request: ChatRequest):
    """
    Answer a question about the analyzed repository using LLM RAG.

    Raises:
        404 — repository not yet analyzed
        400 — empty question
    """
    repo_url = request.repo_url.strip().rstrip("/")
    question = request.question.strip()

    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    print(f"[chat] request — repo={repo_url}")

    store = get_store(repo_url)
    if store is None or store.size == 0:
        print(f"[rag] in-memory store missing — trying DB restore")
        store = _try_restore_store(repo_url)
        
    if store is None or store.size == 0:
        store = _trigger_lightweight_rebuild(repo_url)

    if store is None or store.size == 0:
        raise HTTPException(
            status_code=404,
            detail=(
                "No analysis found for this repository. "
                "Please run an analysis first, then ask questions."
            ),
        )

    print(f"[rag] repo found in store — {store.size} chunks")

    if is_metadata_question(question):
        metadata = get_cached_metadata(repo_url)
        return answer_metadata_question(question, metadata)

    model = get_model()
    retrieved = query_store(store, question, model, top_k=8)
    result = answer_question(question, retrieved)

    return result


# ── Streaming SSE endpoint ────────────────────────────────────────────────────

@router.get("/stream")
def chat_stream(
    repo_url: str = Query(..., description="The analyzed repository URL"),
    question: str = Query(..., description="The question to answer"),
):
    """
    Stream the answer token-by-token using Server-Sent Events.

    Clients receive:
        data: <token>\\n\\n          — individual text tokens
        data: [META] {...}\\n\\n     — JSON with sources + confidence
        data: [DONE]\\n\\n           — stream end sentinel
    """
    repo_url = repo_url.strip().rstrip("/")
    question = question.strip()

    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    print(f"[chat/stream] request — repo={repo_url}")

    store = get_store(repo_url)
    if store is None or store.size == 0:
        print(f"[rag] in-memory store missing (stream) — trying DB restore")
        store = _try_restore_store(repo_url)
        
    if store is None or store.size == 0:
        store = _trigger_lightweight_rebuild(repo_url)

    if store is None or store.size == 0:
        raise HTTPException(
            status_code=404,
            detail=(
                "No analysis found for this repository. "
                "Please run an analysis first, then ask questions."
            ),
        )

    print(f"[rag] repo found in store (stream) — {store.size} chunks")

    if is_metadata_question(question):
        metadata = get_cached_metadata(repo_url)
        def _meta_stream():
            yield from stream_metadata_answer(question, metadata)
        return StreamingResponse(
            _meta_stream(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no",
                "Access-Control-Allow-Origin": "*",
            },
        )

    model = get_model()
    retrieved = query_store(store, question, model, top_k=8)

    def _event_stream():
        try:
            yield from stream_answer_tokens(question, retrieved)
        except Exception as exc:
            import json as _json
            print(f"[stream] error: {exc}")
            yield f"data: ⚠️ Stream error: {str(exc)}\n\n"
            yield f'data: [META] {_json.dumps({"sources": [], "confidence": "low"})}\n\n'
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        _event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",       # disable nginx buffering if present
            "Access-Control-Allow-Origin": "*",
        },
    )
